[build]
  publish = "build"
  command = "npm run build"
  
[[redirects]]
  from = "/account/*"
  to = "/account/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200